# -*- coding: utf-8 -*-
"""minimal app

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/15VxD7BHKJ3obBrOSBTzoCs6biX59SdL4
"""

import streamlit as st
from research_paper_suggestion_ai_agent import arxiv_search

st.title("Research Paper Suggestion AI Agent")
topic = st.text_input("Enter your research topic:")

if st.button("Search") and topic:
    results = arxiv_search(topic)
    for i, p in enumerate(results, 1):
        st.subheader(f"{i}. {p['title']} ({p['published'][:10]})")
        st.write(f"**Authors:** {', '.join(p['authors'])}")
        st.write(f"**Link:** {p['link']}")
        st.write(f"**Summary:** {p['summary'][:300]}...")

st.caption("Powered by arXiv.org")
