# -*- coding: utf-8 -*-
"""Streamlit app

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1lQercGNAk2Gm55x2tlhN77yU3in3qd8D
"""

import streamlit as st
import requests
import xml.etree.ElementTree as ET
from transformers import pipeline

# Try to load the summarization pipeline (BART)
try:
    summarizer = pipeline("summarization", model="facebook/bart-large-cnn")
except Exception:
    summarizer = None
    st.warning("Summarizer pipeline unavailable. Showing plain abstracts.")

def arxiv_search(query, max_results=5):
    search_url = f'http://export.arxiv.org/api/query?search_query=all:{query}&start=0&max_results={max_results}'
    resp = requests.get(search_url)
    papers = []
    if resp.status_code == 200:
        root = ET.fromstring(resp.content)
        for entry in root.findall('{http://www.w3.org/2005/Atom}entry'):
            title = entry.find('{http://www.w3.org/2005/Atom}title').text.strip()
            summary = entry.find('{http://www.w3.org/2005/Atom}summary').text.strip()
            authors = [author.find('{http://www.w3.org/2005/Atom}name').text for author in entry.findall('{http://www.w3.org/2005/Atom}author')]
            published = entry.find('{http://www.w3.org/2005/Atom}published').text
            link = entry.find('{http://www.w3.org/2005/Atom}id').text

            # Generate summary if pipeline available, else plain abstract
            if summarizer:
                try:
                    sum_text = summarizer(summary, max_length=70, min_length=25, do_sample=False)[0]['summary_text']
                except Exception:
                    sum_text = summary
            else:
                sum_text = summary

            papers.append({'title': title,
                           'authors': authors,
                           'published': published,
                           'summary': sum_text,
                           'link': link})
    return papers

# -------------------
# Streamlit UI (TOP LEVEL)
# -------------------
st.title("Research Paper Suggestion AI Agent")
st.write("Enter a research topic below to get research paper recommendations and summaries:")

topic = st.text_input("Research topic or question", "")
max_results = st.slider("Max number of papers", min_value=1, max_value=10, value=5)

if st.button("Search") and topic:
    st.info(f"Searching arXiv for: {topic}")
    results = arxiv_search(topic, max_results)
    if results:
        for i, p in enumerate(results, 1):
            st.markdown(f"### {i}. {p['title']} ({p['published'][:10]})")
            st.write(f"**Authors:** {', '.join(p['authors'])}")
            st.write(f"[View on arXiv]({p['link']})")
            st.write(f"**Summary:** {p['summary'][:450]}...")
            st.markdown("---")
    else:
        st.warning("No papers found for your query.")

st.caption("Powered by arXiv.org")